# NUMPY TUTORIAL

In [1]:
import numpy

In [2]:
numpy.array([1,2,3,4,5,6,7])

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
numpy.array([11,12,13,14,15,16,17,18])

array([11, 12, 13, 14, 15, 16, 17, 18])

In [4]:
import numpy as np

In [5]:
a=np.array([90,92,93,94,95,96,97,98,99])

In [6]:
a

array([90, 92, 93, 94, 95, 96, 97, 98, 99])

In [7]:
a.shape

(9,)

In [8]:
b=np.array([10,20,30,40,50,60,70,80,90,100])

In [9]:
b

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [10]:
b.shape

(10,)

In [11]:
a=np.array([[1,2],[3,4]])

In [12]:
a

array([[1, 2],
       [3, 4]])

In [13]:
a.shape

(2, 2)

In [14]:
b=np.array([[2,3],[4,5],[6,7]])

In [15]:
b

array([[2, 3],
       [4, 5],
       [6, 7]])

# b.shape

In [16]:
c=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [17]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
c.shape

(3, 3)

In [19]:
d=np.array([[1,2,3],[4,5,6]])

In [20]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
d.shape

(2, 3)

In [22]:
e=np.array([[2,3],[4,5],[6,7]])

In [23]:
e

array([[2, 3],
       [4, 5],
       [6, 7]])

In [24]:
e.shape

(3, 2)

In [25]:
a=np.array([[5,5,6],[6,7,3],[7,6,4],[3,4,9]])
a

array([[5, 5, 6],
       [6, 7, 3],
       [7, 6, 4],
       [3, 4, 9]])

In [26]:
a.shape

(4, 3)

In [27]:
f=np.array([[2,3,4,5],[5,6,7,8],[1,2,3,4]])

In [28]:
f.shape

(3, 4)

In [29]:
b=np.array([[1,3],[4,5,],[5,6],[6,7],[7,8]])

In [30]:
b.shape

(5, 2)

In [31]:
b.reshape(2,5)

array([[1, 3, 4, 5, 5],
       [6, 6, 7, 7, 8]])

In [32]:
b.shape

(5, 2)

In [33]:
f.shape

(3, 4)

In [34]:
f.reshape(4,3)

array([[2, 3, 4],
       [5, 5, 6],
       [7, 8, 1],
       [2, 3, 4]])

In [35]:
b=np.array([[77,88],[11,69]])
b

array([[77, 88],
       [11, 69]])

In [36]:
b.shape

(2, 2)

In [37]:
b.min()

11

In [38]:
b.max()

88

In [39]:
b.shape

(2, 2)

In [40]:
b.size

4

In [41]:
a=np.array([[1,2,3,4,5,6,7],[9,8,7,6,5,4,5]])

In [42]:
a

array([[1, 2, 3, 4, 5, 6, 7],
       [9, 8, 7, 6, 5, 4, 5]])

In [43]:
a.shape

(2, 7)

In [44]:
a.reshape(7,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 9],
       [8, 7],
       [6, 5],
       [4, 5]])

In [45]:
a.size

14

In [46]:
a.itemsize

4

In [47]:
#give the data type

a.dtype

dtype('int32')

In [48]:
a.min()

1

In [49]:
a.max()

9

In [50]:
a.itemsize

4

In [51]:
#gives the memrory address

a.data

In [52]:
a=np.array([[1,2]])

In [53]:
a=np.array ([[1,2],[3,4],[5,6],[6,7]],dtype='float64')
# c1-np.array([[1,2],[3,4],[5,6],[6,7]])

a

#c1

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [6., 7.]])

In [54]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [6., 7.]])

In [55]:
a.itemsize

8

In [56]:
a.dtype

dtype('float64')

In [57]:
# number of dimension
a.ndim

2

In [58]:
#gives number of bytes : it is float datatype hence it takes 8 to store the data
a.itemsize

8

In [59]:
a.reshape(2,4)

array([[1., 2., 3., 4.],
       [5., 6., 6., 7.]])

In [60]:
y=np.arange(5)
y

array([0, 1, 2, 3, 4])

In [61]:
x=np.arange(15)

In [62]:
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [63]:
a=x.reshape(3,5)

In [64]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [65]:
x=np.arange(25)

In [66]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [67]:
b=x.reshape(5,5)

In [68]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [69]:
x=np.arange(35)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34]


In [70]:
c=x.reshape(5,7)
c

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34]])

In [71]:
c=np.arange(32).reshape(4,8)
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31]])

In [72]:
c.shape

(4, 8)

In [73]:
c.ndim

2

In [74]:
c.dtype

dtype('int32')

In [75]:
a.itemsize

4

In [76]:
c.size

32

In [77]:
type(c)

numpy.ndarray

In [78]:
b=np.array([6,7,8])
b

array([6, 7, 8])

In [79]:
type(b)

numpy.ndarray

In [80]:
import numpy as np
b=np.array([[1.5,2,5],[4,5,6]],dtype='float32')

In [81]:
b

array([[1.5, 2. , 5. ],
       [4. , 5. , 6. ]], dtype=float32)

In [82]:
ra=np.array([[32,33,34],[44,55,66]])
ra

array([[32, 33, 34],
       [44, 55, 66]])

In [83]:
# Ravel      operation where you can convert one numpy array intp single row i.e ravel
print(ra.ravel())

[32 33 34 44 55 66]


In [104]:
import numpy as np
b=np.array([[1.6,2,3,4],[5,6,7,8]],dtype='int32')
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [105]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [106]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [107]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [114]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
#(start,end,skip or jump)

np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [109]:
b=np.arange(10,30,5)
b

array([10, 15, 20, 25])

In [110]:
b=np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

Broadcasting in Numpy

In [111]:
a=np.array([1.0,2.0,3.0])
b=np.array([2.0,3.0,4.0])
a*b

array([ 2.,  6., 12.])

In [92]:
a=np.array([1.0,2.0,3.0])
b=2.0
a*b

array([2., 4., 6.])

In [93]:
a=np.array([20,30,40,50])
b=np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [94]:
c=a-b
print(c)

[20 29 38 47]


In [95]:
b**2

array([0, 1, 4, 9], dtype=int32)

In [96]:
b=np.random.random([2,3])

In [97]:
b

array([[0.10114381, 0.18088816, 0.70908565],
       [0.73222986, 0.20358803, 0.54119909]])

In [117]:
z=np.random.random([1,7])
z

array([[0.56743545, 0.2731515 , 0.31100176, 0.06441125, 0.1643803 ,
        0.78622517, 0.89199878]])

In [98]:
c=np.ones([2,3])

In [99]:
c

array([[1., 1., 1.],
       [1., 1., 1.]])

In [100]:
d=b+c
d

array([[1.10114381, 1.18088816, 1.70908565],
       [1.73222986, 1.20358803, 1.54119909]])

UNIVERSAL FUNCTIONS

In [121]:
B=np.arange(3)
B

array([0, 1, 2])

In [119]:
B

array([0, 1, 2])

In [122]:
np.exp(B)

array([1.        , 2.71828183, 7.3890561 ])

In [123]:
np.sqrt(B)

array([0.        , 1.        , 1.41421356])

In [124]:
c=np.array([2,1,4])
np.add(B,c)

array([2, 2, 6])

Indexing slicing 

In [125]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [126]:
a[2]

2

In [127]:
a[2:5]

array([2, 3, 4])

In [128]:
a[-1]

9

In [129]:
a[-3]

7

In [130]:
a[-4:]

array([6, 7, 8, 9])

In [131]:
a[-4:-2]

array([6, 7])

In [132]:
d2=np.arange(20)
d2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [134]:
d2[5:]  # slicing from 5th index till the end of array

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [136]:
d3=np.array([np.nan,1,2,3,np.nan,6,7,8])
d3

array([nan,  1.,  2.,  3., nan,  6.,  7.,  8.])

In [138]:
np.random.rand(2,2)  #uniform distributions ------> similar like random

array([[0.62860199, 0.40879179],
       [0.94207395, 0.82331322]])

In [139]:
np.random.rand(2,3)

array([[0.28153292, 0.11000398, 0.80850585],
       [0.81623583, 0.37421788, 0.54540662]])

In [141]:
np.random.randn(2,3)

array([[-0.13045864, -0.60633183, -1.17478486],
       [-0.70971183, -0.01514516,  0.21960299]])