In [2]:
import numpy as np


In [3]:
a=np.array([45,60,34,80,20])

In [4]:
a

array([45, 60, 34, 80, 20])

In [5]:
np.mean(a)

47.8

In [6]:
b=np.array([78,24,57,88,15,32,68])

In [7]:
b

array([78, 24, 57, 88, 15, 32, 68])

In [8]:
c=np.mean(b)

In [9]:
c

51.714285714285715

In [10]:
round(c,2)

51.71

In [11]:
a

array([45, 60, 34, 80, 20])

In [12]:
np.median(a)

45.0

In [13]:
b

array([78, 24, 57, 88, 15, 32, 68])

In [14]:
np.median(b)

57.0

In [15]:
d=np.array([20,55,66,90,15,25])
np.median(d)

40.0

In [16]:
import numpy as np
a=np.array([[3,7,5],[8,4,3],[2,4,9]])

In [17]:
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [18]:
np.median(a)

4.0

In [19]:
np.median(a,axis=0)  # columnswise

array([3., 4., 5.])

In [20]:
np.median(a,axis=1)#rowwise

array([5., 4., 4.])

In [21]:
import numpy as np
a=np.array([[3,7,5],[8,4,3],[2,4,9]])

In [22]:
a

array([[3, 7, 5],
       [8, 4, 3],
       [2, 4, 9]])

In [23]:
np.mean(a)

5.0

In [24]:
np.mean(a,axis=0)

array([4.33333333, 5.        , 5.66666667])

In [25]:
np.mean(a,axis=1)

array([5., 5., 5.])

In [26]:
np.std(a)   # standard deviation

2.309401076758503

In [27]:
np.var(a)

5.333333333333333

In [28]:
a=np.array([45,60,34,80,20])
a

array([45, 60, 34, 80, 20])

In [29]:
a.max()

80

In [30]:
a.min()

20

In [31]:
myrange=a.max()-a.min()

In [32]:
myrange

60

In [33]:
np.var(a)

431.35999999999996

In [34]:
h=np.var(a)
round(h,2)

431.36

In [35]:
np.var(a)

431.35999999999996

In [36]:
np.var(a,axis=0)

431.35999999999996

In [37]:
np.var(a)

431.35999999999996

In [38]:
import pandas as pd
data=pd.read_csv('president_heights.csv')
data

order                    name  height
0       1       George Washington     189
1       2              John Adams     170
2       3        Thomas Jefferson     189
3       4           James Madison     163
4       5            James Monroe     183
5       6       John Quincy Adams     171
6       7          Andrew Jackson     185
7       8        Martin Van Buren     168
8       9  William Henry Harrison     173
9      10              John Tyler     183
10     11           James K. Polk     173
11     12          Zachary Taylor     173
12     13        Millard Fillmore     175
13     14         Franklin Pierce     178
14     15          James Buchanan     183
15     16         Abraham Lincoln     193
16     17          Andrew Johnson     178
17     18        Ulysses S. Grant     173
18     19     Rutherford B. Hayes     174
19     20       James A. Garfield     183
20     21       Chester A. Arthur     183
21     23       Benjamin Harrison     168
22     25        William McKinley     170
23     26      Theodore Roosevelt     178
24     27     William Howard Taft     182
25     28          Woodrow Wilson     180
26     29       Warren G. Harding     183
27     30         Calvin Coolidge     178
28     31          Herbert Hoover     182
29     32   Franklin D. Roosevelt     188
30     33         Harry S. Truman     175
31     34    Dwight D. Eisenhower     179
32     35         John F. Kennedy     183
33     36       Lyndon B. Johnson     193
34     37           Richard Nixon     182
35     38             Gerald Ford     183
36     39            Jimmy Carter     177
37     40           Ronald Reagan     185
38     41       George H. W. Bush     188
39     42            Bill Clinton     188
40     43          George W. Bush     182
41     44            Barack Obama     185

In [42]:
heights=data['height']

In [43]:
print("Mean height:   ",heights.mean())
print("Standard deviation:",heights.std())
print("Minimum height:     ",heights.min())
print("Maximum height:     ",heights.max())

Mean height:    179.73809523809524
Standard deviation: 7.015868855358296
Minimum height:      163
Maximum height:      193


In [41]:
print("Median:       ",np.median(heights))

Median:        182.0


In [46]:
print("Minimum height: ",heights.min())

Minimum height:  163
